### ISSUE TITLE
Error in annotation

### ISSUE THREAD

**Issue by shouwang2014** [Nibo512/MachineVision#1]
Is that "赚" means "convert to" ?

**Comment by Nibo512** [comment]
是的






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hu ***@***.***&gt;; 
发送时间: 2023年4月6日(星期四) 下午5:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [Nibo512/MachineVision] Error in annotation (Issue #1)





 
Is that "赚" means "convert to" ?
